#
# spec file for package python-mcp-server-mlm
#
# Copyright (c) 2025 SUSE LLC
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via https://bugs.opensuse.org/
#


%{?sle15_python_module_pythons}
%if 0%{?suse_version} > 1500
%bcond_without libalternatives
%else
%bcond_with libalternatives
%endif
%global p_version 0.5.2
%global git_revision %(tar xfO %{SOURCE0} mcp-server-uyuni-%{p_version}/last-commit)

Name:           python-mcp-server-mlm
Version:        %{p_version}+git%{git_revision}
Release:        0
Summary:        Model Context Protocol Server for Uyuni Server API
License:        Apache-2.0
URL:            https://github.com/uyuni-project/mcp-server-uyuni
Source:         mcp-server-uyuni-%{p_version}.tar.gz

BuildRequires:  %{python_module pip}
BuildRequires:  %{python_module setuptools}
BuildRequires:  %{python_module wheel}
BuildRequires:  %{python_module hatchling}
BuildRequires:  fdupes
BuildRequires:  python-rpm-macros
Requires:       python-fastmcp >= 2.6.0
# List of python dependencies from uv.lock generated by pydeps.py
Requires:       %{python_module annotated-doc = 0.0.4}
Requires:       %{python_module annotated-types = 0.7.0}
Requires:       %{python_module anyio = 4.12.1}
Requires:       %{python_module attrs = 26.1.0}
Requires:       %{python_module Authlib = 1.6.9}
Requires:       %{python_module beartype = 0.22.9}
Requires:       %{python_module certifi = 2026.2.25}
Requires:       %{python_module cffi = 2.0.0}
Requires:       %{python_module click = 8.3.1}
Requires:       %{python_module cloudpickle = 3.1.2}
Requires:       %{python_module cronsim = 2.7}
Requires:       %{python_module cryptography = 44.0.3}
Requires:       %{python_module cyclopts = 4.10.1}
Requires:       %{python_module docstring-parser = 0.17.0}
Requires:       %{python_module docutils = 0.22.4}
Requires:       %{python_module exceptiongroup = 1.3.1}
Requires:       %{python_module fakeredis = 2.34.1}
Requires:       %{python_module fastmcp = 2.14.5}
Requires:       %{python_module h11 = 0.16.0}
Requires:       %{python_module httpcore = 1.0.9}
Requires:       %{python_module httpx = 0.28.1}
Requires:       %{python_module httpx-sse = 0.4.3}
Requires:       %{python_module idna = 3.11}
Requires:       %{python_module importlib-metadata = 8.7.1}
Requires:       %{python_module jsonref = 1.1.0}
Requires:       %{python_module jsonschema = 4.26.0}
Requires:       %{python_module jsonschema-path = 0.4.5}
Requires:       %{python_module jsonschema-specifications = 2025.9.1}
Requires:       %{python_module markdown-it-py = 4.0.0}
Requires:       %{python_module mcp = 1.26.0}
Requires:       %{python_module mdurl = 0.1.2}
Requires:       %{python_module openapi-pydantic = 0.5.1}
Requires:       %{python_module opentelemetry-api = 1.40.0}
Requires:       %{python_module packaging = 26.0}
Requires:       %{python_module pathable = 0.5.0}
Requires:       %{python_module platformdirs = 4.9.4}
Requires:       %{python_module prometheus-client = 0.24.1}
Requires:       %{python_module py-key-value-aio = 0.3.0}
Requires:       %{python_module py-key-value-shared = 0.3.0}
Requires:       %{python_module pycparser = 3.0}
Requires:       %{python_module pydantic = 2.12.5}
Requires:       %{python_module pydantic-core = 2.41.5}
Requires:       %{python_module pydantic-settings = 2.13.1}
Requires:       %{python_module pydocket = 0.18.2}
Requires:       %{python_module pygments = 2.20.0}
Requires:       %{python_module pyjwt = 2.12.1}
Requires:       %{python_module pyperclip = 1.11.0}
Requires:       %{pythons}-python-dotenv = 1.2.2
Requires:       %{python_module python-json-logger = 4.0.0}
Requires:       %{pythons}-python-multipart = 0.0.22
Requires:       %{python_module PyYAML = 6.0.3}
Requires:       %{python_module redis = 7.4.0}
Requires:       %{python_module referencing = 0.37.0}
Requires:       %{python_module rich = 14.3.3}
Requires:       %{python_module rich-rst = 1.3.2}
Requires:       %{python_module rpds-py = 0.30.0}
Requires:       %{python_module shellingham = 1.5.4}
Requires:       %{python_module sortedcontainers = 2.4.0}
Requires:       %{python_module sse-starlette = 3.3.3}
Requires:       %{python_module starlette = 1.0.0}
Requires:       %{python_module typer = 0.24.1}
Requires:       %{python_module typing-extensions = 4.15.0}
Requires:       %{python_module typing-inspection = 0.4.2}
Requires:       %{python_module uncalled-for = 0.2.0}
Requires:       %{python_module uvicorn = 0.42.0}
Requires:       %{python_module websockets = 16.0}
Requires:       %{python_module zipp = 3.23.0}
# End
Provides:       %{name} = %{p_version}  

BuildArch:      noarch

%if %{with libalternatives}
BuildRequires:  alts
Requires:       alts
%else
Requires(post): update-alternatives
Requires(postun): update-alternatives
%endif
%python_subpackages

%description
Model Context Protocol Server for Uyuni/MLM Server API.

%prep
%autosetup -p1 -n mcp-server-uyuni-%{p_version}

%build
%pyproject_wheel

%install
%pyproject_install
%python_expand %fdupes %{buildroot}%{$python_sitelib}
%python_clone -a %{buildroot}%{_bindir}/mcp-server-uyuni

%post
%python_install_alternative mcp-server-uyuni

%postun
%python_uninstall_alternative mcp-server-uyuni

%files %{python_files}
%license LICENSE
%python_alternative %{_bindir}/mcp-server-uyuni
%{python_sitelib}/mcp_server_uyuni*

%changelog
